name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3


  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: setup-environment
      - run: npm ci
      - run: npm test

  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: setup-environment
      - run: npm build
